
 LogLevel  3
 
 LogDir  "default"

 DefaultRate   0

 DefaultPitch   0

 DefaultPitchRange   0

 DefaultVolume 100
 
 DefaultLanguage   en-US

 SymbolsPreproc "char"
 
 AudioOutputMethod   pulse

 AddModule "edge" "sd_generic" "edge.conf"
 DefaultModule edge
 LanguageDefaultModule "en" "edge"

 Include "clients/*.conf"
