# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# Monitor configuration
## INTEGRATED
monitor = eDP-1,preferred,0x0,1
#monitor = eDP-1,disable

## DORM ROOM
#monitor = HDMI-A-2,preferred,+1920x0,1
monitor = HDMI-A-2,preferred,0x-1080,1
#monitor = HDMI-A-2,preferred,0x0,1

## COMPUTER LAB
#monitor = DP-2,preferred,0x-1440,1
#monitor = DP-2,preferred,0x0,1
#monitor = HDMI-A-2,preferred,0x-1440,1
#monitor = HDMI-A-2,preferred,0x0,1

## Vertical Screen
monitor = DP-1,preferred,1920x-840,1,transform,1

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
# monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1

general {
    gaps_in = 0
    gaps_out = 0

    border_size = 0
    col.active_border = rgba(0DB7D4FF)

    resize_on_border = false
}

dwindle {
    smart_split = true
}

decoration {
    rounding = 0

    blur {
        enabled = false
        noise = 0.15
        contrast = 0.2
        vibrancy = 0.8
        vibrancy_darkness = 0.8
    }

    shadow {
        enabled = false
    }

    dim_inactive = false
    dim_strength = 0.025
    dim_special = 0.07
}

animations {
    enabled = false
}

input {
    touchpad {
        natural_scroll = no
        scroll_factor = 2.0
    }

    sensitivity = 0.6
    force_no_accel = false
}

misc {
    zoom_disable_aa = false
}

device {
    name = tpps/2-ibm-trackpoint
    enabled = true
}

$KEYBOARD_ENABLED = true
device {
    name = at-translated-set-2-keyboard
    enabled = $KEYBOARD_ENABLED
}

$TOUCHPAD_ENABLED = true
device {
    name = synaptics-tm3276-022
    enabled = $TOUCHPAD_ENABLED
}

device {
    name = logitech-g305-1
    sensitivity = -0.2
}

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(000000)
        workspace_method = first 1
    }
}
