Debug "1"

DefaultVoice "en-US-SteffanNeural"

# Prevents speechd from cutting text into too many chunks by specifying a rarely used symbol and a limit
GenericDelimiters "˨"
GenericMaxChunkLength 1000000

GenericLanguage "en" "en-us" "utf-8"

# Dependency for edge-playback
GenericCmdDependency "edge-playback"
GenericCmdDependency "mpv"

# GenericExecuteSynth "printf %s \"$DATA\" | /home/bruv/bin/edge-tts-wrapper $VOICE $RATE"
GenericExecuteSynth "printf %s -- '$DATA' | /home/bruv/bin/edge-tts-wrapper $VOICE $RATE"

# AddVoice "en" "FEMALE1" "en-US-AnaNeural"
# AddVoice "en" "MALE1" "en-US-AndrewMultilingualNeural"
# AddVoice "en" "MALE1" "en-US-AndrewNeural"
# AddVoice "en" "FEMALE1" "en-US-AriaNeural"
# AddVoice "en" "FEMALE1" "en-US-AvaMultilingualNeural"
# AddVoice "en" "FEMALE1" "en-US-AvaNeural"
# AddVoice "en" "MALE1" "en-US-BrianMultilingualNeural"
# AddVoice "en" "MALE1" "en-US-BrianNeural"
# AddVoice "en" "MALE1" "en-US-ChristopherNeural"
# AddVoice "en" "FEMALE1" "en-US-EmmaMultilingualNeural"
# AddVoice "en" "FEMALE1" "en-US-EmmaNeural"
# AddVoice "en" "MALE1" "en-US-EricNeural"
# AddVoice "en" "MALE1" "en-US-GuyNeural"
# AddVoice "en" "FEMALE1" "en-US-JennyNeural"
# AddVoice "en" "FEMALE1" "en-US-MichelleNeural"
# AddVoice "en" "MALE1" "en-US-RogerNeural"
AddVoice "en" "MALE1" "en-US-SteffanNeural"
