# Originally from: https://github.com/ken107/read-aloud/issues/375#issuecomment-1937517761
DefaultVoice "en/en_US/amy/medium/en_US-amy-medium.onnx"

# Specifying a rarely used symbol & big limit so that speech-dispatcher doesn't cut text into chunks:
GenericDelimiters "˨"
GenericMaxChunkLength 1000000

GenericLanguage "en" "en-us" "utf-8"

GenericCmdDependency "sox"
GenericCmdDependency "aplay"

GenericExecuteSynth \
"echo '$DATA' | /usr/bin/piper-tts --model '/usr/share/piper-voices/$VOICE' --output_raw | sox -r 22050 -c 1 -b 16 -e signed-integer -t raw - -t wav - tempo $RATE pitch $PITCH norm | aplay -r 22050 -f S16_LE -t raw -"

GenericRateAdd 1
GenericPitchAdd 1
GenericVolumeAdd 1
GenericRateMultiply 1
GenericPitchMultiply 1000

AddVoice "en" "MALE1" "en/en_US/sam/medium/en_US-sam-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/ryan/medium/en_US-ryan-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/ryan/low/en_US-ryan-low.onnx"
AddVoice "en" "MALE1" "en/en_US/ryan/high/en_US-ryan-high.onnx"
AddVoice "en" "MALE1" "en/en_US/reza_ibrahim/medium/en_US-reza_ibrahim-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/norman/medium/en_US-norman-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/ljspeech/high/en_US-ljspeech-high.onnx"
AddVoice "en" "MALE1" "en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/libritts/high/en_US-libritts-high.onnx"
AddVoice "en" "MALE1" "en/en_US/lessac/medium/en_US-lessac-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/lessac/low/en_US-lessac-low.onnx"
AddVoice "en" "MALE1" "en/en_US/lessac/high/en_US-lessac-high.onnx"
AddVoice "en" "MALE1" "en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/kusal/medium/en_US-kusal-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/kristin/medium/en_US-kristin-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/kathleen/low/en_US-kathleen-low.onnx"
AddVoice "en" "MALE1" "en/en_US/john/medium/en_US-john-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/joe/medium/en_US-joe-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx"
AddVoice "en" "MALE1" "en/en_US/danny/low/en_US-danny-low.onnx"
AddVoice "en" "MALE1" "en/en_US/bryce/medium/en_US-bryce-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/arctic/medium/en_US-arctic-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/amy/medium/en_US-amy-medium.onnx"
AddVoice "en" "FEMALE1" "en/en_US/amy/low/en_US-amy-low.onnx"